name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: pwd
      - name: Checkout repository
        uses: actions/checkout@v3 
      - run: ls -la
      - run: pip install pytest 
      - run: pytest test_lib.py